version: '3'
services:
  api:
    build: .
    container_name: "transformer_api"
    volumes:
      - ./app/:/usr/src/application/app:ro
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload